# Generated by Django 4.1.3 on 2024-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='quatMoradia',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='quatQ',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
