# Generated by Django 4.1.3 on 2024-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_department_quatmoradia_department_quatq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AlterField(
            model_name='department',
            name='quatMoradia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='quatQ',
            field=models.TextField(),
        ),
    ]
