# Generated by Django 4.1.3 on 2024-04-17 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_remove_department_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='status',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='address',
            new_name='nacionlidade',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='salary',
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.department')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.position')),
            ],
        ),
    ]
