# Generated by Django 4.1.3 on 2024-04-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_predio_apartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='date_updated',
        ),
    ]
