# Generated by Django 4.1.3 on 2024-04-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_remove_predio_date_added_remove_predio_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='quadra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.department'),
        ),
    ]
