# Generated by Django 4.1.3 on 2024-04-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_position_quadra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='quadra',
            new_name='department_id',
        ),
    ]
