# Generated by Django 4.1.3 on 2024-04-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0014_remove_predio_quadra_predio_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.IntegerField(),
        ),
    ]
