# Generated by Django 4.1.3 on 2024-04-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0015_alter_position_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='position',
            name='date_updated',
        ),
    ]
