# Generated by Django 4.1.3 on 2024-04-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0017_remove_position_department_id_position_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='position',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='position',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.department'),
        ),
    ]
