# Generated by Django 4.1.3 on 2024-04-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0018_remove_position_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department_id',
        ),
    ]
