# Generated by Django 4.1.3 on 2024-04-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0020_position_date_added_position_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_information.department'),
        ),
    ]
