# Generated by Django 4.1.3 on 2024-04-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0022_alter_position_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='department_id',
        ),
    ]
