# Generated by Django 4.1.3 on 2024-04-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0023_remove_predio_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.department'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='loja',
            field=models.TextField(),
        ),
    ]
