# Generated by Django 4.1.3 on 2024-04-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0024_predio_department_id_alter_predio_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='loja',
            field=models.IntegerField(),
        ),
    ]
