# Generated by Django 4.1.3 on 2024-04-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0025_alter_predio_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='name',
            field=models.TextField(),
        ),
    ]
