# Generated by Django 4.1.3 on 2024-05-03 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0026_alter_apartamento_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='position_id',
        ),
        migrations.AddField(
            model_name='contrato',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.apartamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='moradia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.position'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='termos_contrato',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_contratual',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
