# Generated by Django 4.1.3 on 2024-05-03 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0027_remove_contrato_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
