# Generated by Django 4.1.3 on 2024-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0028_contrato_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='nacionlidade',
            field=models.CharField(choices=[('Angolano', 'Angolan'), ('Argelino', 'Algerian'), ('Americano', 'American'), ('Argentino', 'Argentinian'), ('Australiano', 'Australian'), ('Austríaco', 'Austrian'), ('Bangladeshiano', 'Bangladeshi'), ('Belga', 'Belgian'), ('Brasileiro', 'Brazilian'), ('Burundiano', 'Burundian'), ('Camarones', 'Cameroonian'), ('Comorense', 'Comoran'), ('Congolês', 'Congolese'), ('Canadense', 'Canadian'), ('Chinês', 'Chinese'), ('Colombiano', 'Colombian'), ('Cubano', 'Cuban'), ('Dinamarquês', 'Danish'), ('Egípcio', 'Egyptian'), ('Inglês', 'English'), ('Francês', 'French'), ('Alemão', 'German'), ('Grego', 'Greek'), ('Haitiano', 'Haitian'), ('Coreano', 'Korean'), ('Moçambicano', 'Mozambican'), ('Namibiano', 'Namibian'), ('Nigerino', 'Nigerien'), ('Nigeriano', 'Nigerian'), ('Ruandês', 'Rwandan'), ('Senegalês', 'Senegalese')], max_length=14),
        ),
    ]
