# Generated by Django 4.1.3 on 2024-05-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0029_alter_employees_nacionlidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='nacionlidade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
