# Generated by Django 4.1.3 on 2024-05-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0030_alter_employees_nacionlidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(default=None, null=True),
        ),
    ]
