# Generated by Django 4.1.3 on 2024-05-31 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0031_alter_contrato_data_fim_alter_contrato_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=None, null=True)),
                ('valor_contratual', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('termos_contrato', models.TextField(default='')),
                ('data_assinatura', models.DateField(default=django.utils.timezone.now)),
                ('forma_pagamento', models.CharField(default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.apartamento')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
                ('moradia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.position')),
            ],
        ),
    ]
