# Generated by Django 4.1.3 on 2024-05-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0032_contrato1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_contratual',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
