# Generated by Django 4.1.3 on 2024-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0034_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_contratual',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
