# Generated by Django 4.1.3 on 2024-06-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0035_alter_contrato_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
    ]
