# Generated by Django 4.1.3 on 2024-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0037_remove_contrato1_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato1',
            name='forma_pagamento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
