# Generated by Django 4.1.3 on 2024-06-11 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0040_alter_predio_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.predio')),
            ],
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
