# Generated by Django 4.1.3 on 2024-06-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0041_loja1_delete_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='loja',
        ),
    ]
