# Generated by Django 4.1.3 on 2024-06-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0042_remove_predio_loja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loja1',
        ),
    ]
