# Generated by Django 4.1.3 on 2024-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0044_loja_predio_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='loja',
            field=models.IntegerField(),
        ),
    ]
