# Generated by Django 4.1.3 on 2024-06-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0046_contrato2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato2',
            old_name='loja',
            new_name='apartamento',
        ),
    ]
