# Generated by Django 4.1.3 on 2024-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0048_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='mes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
